"""Model Like\Dislikdsadase

Revision ID: 1091bdd00731
Revises: 9aec3d6464ad
Create Date: 2025-10-15 15:27:19.064680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1091bdd00731'
down_revision: Union[str, Sequence[str], None] = '9aec3d6464ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('target_type', sa.String(length=10), nullable=False))
    op.add_column('comments', sa.Column('target_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('unique_movie_user_comment'), 'comments', type_='unique')
    op.drop_constraint(op.f('comments_movie_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_movie_id_fkey'), 'comments', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('unique_movie_user_comment'), 'comments', ['movie_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('comments', 'target_id')
    op.drop_column('comments', 'target_type')
    # ### end Alembic commands ###
